export const marks = [
  {
    name: "Data Science",
    code: "21CSS303T",
    type: "Theory",
    marks: [
      {
        name: "FT-I",
        mark: "5.00",
        total: "5.00",
      },
      {
        name: "FT-II",
        mark: "13.50",
        total: "15.00",
      },
    ],
    credit: "2",
    total: "18.50/20",
  },
  {
    name: "Software Engineering and Project Management",
    code: "21CSC303J",
    type: "Theory",
    marks: [
      {
        name: "FJ-I",
        mark: "14.10",
        total: "15.00",
      },
    ],
    credit: "3",
    total: "14.10/15",
  },
  {
    name: "Compiler Design",
    code: "21CSC304J",
    type: "Theory",
    marks: [
      {
        name: "FJ-I",
        mark: "9.10",
        total: "15.00",
      },
    ],
    credit: "3",
    total: "9.10/15",
  },
  {
    name: "Indian Traditional Knowledge",
    code: "21LEM302T",
    type: "Practical",
    marks: [
      {
        name: "FML-I",
        mark: "28.00",
        total: "30.00",
      },
    ],
    credit: "0",
    total: "28.00/30",
  },
  {
    name: "Software Engineering and Project Management",
    code: "21CSC303J",
    type: "Practical",
    marks: [],
    credit: "3",
    total: null,
  },
  {
    name: "Compiler Design",
    code: "21CSC304J",
    type: "Practical",
    marks: [],
    credit: "3",
    total: null,
  },
  {
    name: "Software Engineering in Artificial Intelligence",
    code: "21CSE312P",
    type: "Theory",
    marks: [],
    credit: "3",
    total: null,
  },
  {
    name: "GPU Powered Computing",
    code: "21CSE309J",
    type: "Theory",
    marks: [
      {
        name: "FJ-I",
        mark: "12.30",
        total: "15.00",
      },
    ],
    credit: "3",
    total: "12.30/15",
  },
  {
    name: "Project",
    code: "21CSP302L",
    type: "Practical",
    marks: [],
    credit: "3",
    total: null,
  },
  {
    name: "Introduction to Robotics",
    code: "21MEO106T",
    type: "Theory",
    marks: [
      {
        name: "FT-I",
        mark: "4.50",
        total: "5.00",
      },
      {
        name: "FT-II",
        mark: "12.80",
        total: "15.00",
      },
    ],
    credit: "3",
    total: "17.30/20",
  },
  {
    name: "GPU Powered Computing",
    code: "21CSE309J",
    type: "Practical",
    marks: [],
    credit: "3",
    total: null,
  },
];

export const user = {
  roll: "RA2211026010546",
  name: "JACK WAGHAN A S",
  program: "B.Tech",
  department: "Computer Science and Engineering",
  specialisation: "CS AIML",
  semester: "6",
  batch: "1",
  section: "AA1",
};

export const timetable = {
  "0": {
    "08:00 - 08:50": {
      title: "Software Engineering in Artificial Intelligence",
      code: "21CSE312P",
      type: "Theory",
      credit: "3",
      room: "TP 303",
      category: "Professional Elective",
    },
    "08:50 - 09:40": {
      title: "Software Engineering in Artificial Intelligence",
      code: "21CSE312P",
      type: "Theory",
      credit: "3",
      room: "TP 303",
      category: "Professional Elective",
    },
    "09:45 - 10:35": {
      title: "Data Science",
      code: "21CSS303T",
      type: "Theory",
      credit: "2",
      room: "TP 403",
      category: "Engineering Science",
    },
    "10:40 - 11:30": {
      title: "Data Science",
      code: "21CSS303T",
      type: "Theory",
      credit: "2",
      room: "TP 403",
      category: "Engineering Science",
    },
    "11:35 - 12:25": {
      title: "Introduction to Robotics",
      code: "21MEO106T",
      type: "Theory",
      credit: "3",
      room: "B301",
      category: "Open Elective",
    },
    "04:50 - 05:30": {
      title: "Project",
      code: "21CSP302L",
      type: "LAB",
      credit: "3",
      room: "UB703",
      category: "Project Course",
    },
    "05:30 - 06:10": {
      title: "Project",
      code: "21CSP302L",
      type: "LAB",
      credit: "3",
      room: "UB703",
      category: "Project Course",
    },
  },
  "1": {
    "12:30 - 01:20": {
      title: "Software Engineering and Project Management",
      code: "21CSC303J",
      type: "Theory",
      credit: "3",
      room: "TP 403",
      category: "Professional Core",
    },
    "01:25 - 02:15": {
      title: "Software Engineering and Project Management",
      code: "21CSC303J",
      type: "Theory",
      credit: "3",
      room: "TP 403",
      category: "Professional Core",
    },
    "02:20 - 03:10": {
      title: "Introduction to Robotics",
      code: "21MEO106T",
      type: "Theory",
      credit: "3",
      room: "B301",
      category: "Open Elective",
    },
    "03:10 - 04:00": {
      title: "Introduction to Robotics",
      code: "21MEO106T",
      type: "Theory",
      credit: "3",
      room: "B301",
      category: "Open Elective",
    },
    "04:00 - 04:50": {
      title: "Software Engineering in Artificial Intelligence",
      code: "21CSE312P",
      type: "Theory",
      credit: "3",
      room: "TP 303",
      category: "Professional Elective",
    },
  },
  "2": {
    "08:00 - 08:50": {
      title: "Compiler Design",
      code: "21CSC304J",
      type: "Theory",
      credit: "3",
      room: "TP 403",
      category: "Professional Core",
    },
    "08:50 - 09:40": {
      title: "Compiler Design",
      code: "21CSC304J",
      type: "Theory",
      credit: "3",
      room: "TP 403",
      category: "Professional Core",
    },
    "09:45 - 10:35": {
      title: "Software Engineering in Artificial Intelligence",
      code: "21CSE312P",
      type: "Theory",
      credit: "3",
      room: "TP 303",
      category: "Professional Elective",
    },
    "10:40 - 11:30": {
      title: "GPU Powered Computing",
      code: "21CSE309J",
      type: "Theory",
      credit: "3",
      room: "TP 703",
      category: "Professional Elective",
    },
    "11:35 - 12:25": {
      title: "Software Engineering and Project Management",
      code: "21CSC303J",
      type: "Theory",
      credit: "3",
      room: "TP 403",
      category: "Professional Core",
    },
    "04:50 - 05:30": {
      title: "Indian Traditional Knowledge",
      code: "21LEM302T",
      type: "LAB",
      credit: "0",
      room: "UB801",
      category: "Mandatory",
    },
    "05:30 - 06:10": {
      title: "Indian Traditional Knowledge",
      code: "21LEM302T",
      type: "LAB",
      credit: "0",
      room: "UB801",
      category: "Mandatory",
    },
  },
  "3": {
    "08:00 - 08:50": {
      title: "Software Engineering and Project Management",
      code: "21CSC303J",
      type: "LAB",
      credit: "3",
      room: "UB703",
      category: "Professional Core",
    },
    "08:50 - 09:40": {
      title: "Software Engineering and Project Management",
      code: "21CSC303J",
      type: "LAB",
      credit: "3",
      room: "UB703",
      category: "Professional Core",
    },
    "12:30 - 01:20": {
      title: "GPU Powered Computing",
      code: "21CSE309J",
      type: "Theory",
      credit: "3",
      room: "TP 703",
      category: "Professional Elective",
    },
    "01:25 - 02:15": {
      title: "GPU Powered Computing",
      code: "21CSE309J",
      type: "Theory",
      credit: "3",
      room: "TP 703",
      category: "Professional Elective",
    },
    "02:20 - 03:10": {
      title: "Software Engineering and Project Management",
      code: "21CSC303J",
      type: "Theory",
      credit: "3",
      room: "TP 403",
      category: "Professional Core",
    },
    "04:00 - 04:50": {
      title: "Compiler Design",
      code: "21CSC304J",
      type: "Theory",
      credit: "3",
      room: "TP 403",
      category: "Professional Core",
    },
    "04:50 - 05:30": {
      title: "GPU Powered Computing",
      code: "21CSE309J",
      type: "LAB",
      credit: "3",
      room: "NA",
      category: "Professional Elective",
    },
    "05:30 - 06:10": {
      title: "GPU Powered Computing",
      code: "21CSE309J",
      type: "LAB",
      credit: "3",
      room: "NA",
      category: "Professional Elective",
    },
  },
  "4": {
    "09:45 - 10:35": {
      title: "Compiler Design",
      code: "21CSC304J",
      type: "Theory",
      credit: "3",
      room: "TP 403",
      category: "Professional Core",
    },
    "10:40 - 11:30": {
      title: "Data Science",
      code: "21CSS303T",
      type: "Theory",
      credit: "2",
      room: "TP 403",
      category: "Engineering Science",
    },
    "11:35 - 12:25": {
      title: "GPU Powered Computing",
      code: "21CSE309J",
      type: "Theory",
      credit: "3",
      room: "TP 703",
      category: "Professional Elective",
    },
    "01:25 - 02:15": {
      title: "Compiler Design",
      code: "21CSC304J",
      type: "LAB",
      credit: "3",
      room: "UB1209",
      category: "Professional Core",
    },
    "02:20 - 03:10": {
      title: "Compiler Design",
      code: "21CSC304J",
      type: "LAB",
      credit: "3",
      room: "UB1209",
      category: "Professional Core",
    },
  },
};

export const planner = {
  "Jan '25": [
    { date: "1", day: "Wed", sp: "New Year 's  - Holiday", dayo: " - " },
    { date: "2", day: "Thu", sp: "", dayo: " - " },
    { date: "3", day: "Fri", sp: "", dayo: " - " },
    { date: "4", day: "Sat", sp: "", dayo: " - " },
    { date: "5", day: "Sun", sp: "", dayo: " - " },
    { date: "6", day: "Mon", sp: "", dayo: " - " },
    { date: "7", day: "Tue", sp: "", dayo: " - " },
    {
      date: "8",
      day: "Wed",
      sp: "Commencement of - EVEN Semester Classes for All Programs",
      dayo: "1",
    },
    { date: "9", day: "Thu", sp: "", dayo: "2" },
    { date: "10", day: "Fri", sp: "", dayo: "3" },
    { date: "11", day: "Sat", sp: "", dayo: " - " },
    { date: "12", day: "Sun", sp: "", dayo: " - " },
    { date: "13", day: "Mon", sp: "", dayo: "4" },
    { date: "14", day: "Tue", sp: "Pongal - Holiday", dayo: " - " },
    { date: "15", day: "Wed", sp: "Thiruvalluvar Day - Holiday", dayo: " - " },
    { date: "16", day: "Thu", sp: "Uzhavar thirunal - Holiday", dayo: " - " },
    { date: "17", day: "Fri", sp: "", dayo: " - " },
    { date: "18", day: "Sat", sp: "", dayo: " - " },
    { date: "19", day: "Sun", sp: "", dayo: " - " },
    { date: "20", day: "Mon", sp: "", dayo: "5" },
    { date: "21", day: "Tue", sp: "", dayo: "1" },
    { date: "22", day: "Wed", sp: "", dayo: "2" },
    { date: "23", day: "Thu", sp: "", dayo: "3" },
    { date: "24", day: "Fri", sp: "", dayo: "4" },
    { date: "25", day: "Sat", sp: "", dayo: "5" },
    { date: "26", day: "Sun", sp: "Republic Day - Holiday", dayo: " - " },
    { date: "27", day: "Mon", sp: "", dayo: "1" },
    { date: "28", day: "Tue", sp: "", dayo: "2" },
    { date: "29", day: "Wed", sp: "", dayo: "3" },
    { date: "30", day: "Thu", sp: "", dayo: "4" },
    { date: "31", day: "Fri", sp: "", dayo: "5" },
  ],
  "Feb '25": [
    { date: "1", day: "Sat", sp: "", dayo: " - " },
    { date: "2", day: "Sun", sp: "", dayo: " - " },
    { date: "3", day: "Mon", sp: "", dayo: "1" },
    { date: "4", day: "Tue", sp: "", dayo: "2" },
    { date: "5", day: "Wed", sp: "", dayo: "3" },
    { date: "6", day: "Thu", sp: "", dayo: "4" },
    { date: "7", day: "Fri", sp: "", dayo: "5" },
    { date: "8", day: "Sat", sp: "", dayo: " - " },
    { date: "9", day: "Sun", sp: "", dayo: " - " },
    { date: "10", day: "Mon", sp: "", dayo: "1" },
    { date: "11", day: "Tue", sp: "Thaipoosam - Holiday", dayo: " - " },
    { date: "12", day: "Wed", sp: "", dayo: "2" },
    { date: "13", day: "Thu", sp: "", dayo: "3" },
    { date: "14", day: "Fri", sp: "", dayo: "4" },
    { date: "15", day: "Sat", sp: "", dayo: " - " },
    { date: "16", day: "Sun", sp: "", dayo: " - " },
    { date: "17", day: "Mon", sp: "", dayo: "5" },
    { date: "18", day: "Tue", sp: "", dayo: "1" },
    { date: "19", day: "Wed", sp: "", dayo: "2" },
    { date: "20", day: "Thu", sp: "", dayo: "3" },
    { date: "21", day: "Fri", sp: "", dayo: "4" },
    { date: "22", day: "Sat", sp: "", dayo: " - " },
    { date: "23", day: "Sun", sp: "", dayo: " - " },
    { date: "24", day: "Mon", sp: "", dayo: "5" },
    { date: "25", day: "Tue", sp: "", dayo: "1" },
    { date: "26", day: "Wed", sp: "", dayo: "2" },
    { date: "27", day: "Thu", sp: "", dayo: "3" },
    { date: "28", day: "Fri", sp: "", dayo: "4" },
  ],
  "Mar '25": [
    { date: "1", day: "Sat", sp: "", dayo: " - " },
    { date: "2", day: "Sun", sp: "", dayo: " - " },
    { date: "3", day: "Mon", sp: "", dayo: "5" },
    { date: "4", day: "Tue", sp: "", dayo: "1" },
    { date: "5", day: "Wed", sp: "", dayo: "2" },
    { date: "6", day: "Thu", sp: "", dayo: "3" },
    { date: "7", day: "Fri", sp: "", dayo: "4" },
    { date: "8", day: "Sat", sp: "", dayo: " - " },
    { date: "9", day: "Sun", sp: "", dayo: " - " },
    { date: "10", day: "Mon", sp: "", dayo: "5" },
    { date: "11", day: "Tue", sp: "", dayo: "1" },
    { date: "12", day: "Wed", sp: "", dayo: "2" },
    { date: "13", day: "Thu", sp: "", dayo: "3" },
    { date: "14", day: "Fri", sp: "", dayo: " - " },
    { date: "15", day: "Sat", sp: "", dayo: " - " },
    { date: "16", day: "Sun", sp: "", dayo: " - " },
    { date: "17", day: "Mon", sp: "", dayo: "4" },
    { date: "18", day: "Tue", sp: "", dayo: "5" },
    { date: "19", day: "Wed", sp: "", dayo: "1" },
    { date: "20", day: "Thu", sp: "", dayo: "2" },
    { date: "21", day: "Fri", sp: "", dayo: "3" },
    { date: "22", day: "Sat", sp: "", dayo: " - " },
    { date: "23", day: "Sun", sp: "", dayo: " - " },
    { date: "24", day: "Mon", sp: "", dayo: "4" },
    { date: "25", day: "Tue", sp: "", dayo: "5" },
    { date: "26", day: "Wed", sp: "", dayo: "1" },
    { date: "27", day: "Thu", sp: "", dayo: "2" },
    { date: "28", day: "Fri", sp: "", dayo: "3" },
    { date: "29", day: "Sat", sp: "", dayo: " - " },
    {
      date: "30",
      day: "Sun",
      sp: "Telugu New Year's Day - Holiday",
      dayo: " - ",
    },
    { date: "31", day: "Mon", sp: "Ramzan - Holiday", dayo: " - " },
  ],
  "Apr '25": [
    { date: "1", day: "Tue", sp: "", dayo: "4" },
    { date: "2", day: "Wed", sp: "", dayo: "5" },
    { date: "3", day: "Thu", sp: "", dayo: "1" },
    { date: "4", day: "Fri", sp: "", dayo: "2" },
    { date: "5", day: "Sat", sp: "", dayo: " - " },
    { date: "6", day: "Sun", sp: "", dayo: " - " },
    { date: "7", day: "Mon", sp: "", dayo: "3" },
    { date: "8", day: "Tue", sp: "", dayo: "4" },
    { date: "9", day: "Wed", sp: "", dayo: "5" },
    { date: "10", day: "Thu", sp: "Mahaveer jayanthi - Holiday", dayo: " - " },
    { date: "11", day: "Fri", sp: "", dayo: "1" },
    { date: "12", day: "Sat", sp: "", dayo: " - " },
    { date: "13", day: "Sun", sp: "", dayo: " - " },
    {
      date: "14",
      day: "Mon",
      sp: "Tamil New Year's Day - Holiday",
      dayo: " - ",
    },
    { date: "15", day: "Tue", sp: "", dayo: "2" },
    { date: "16", day: "Wed", sp: "", dayo: "3" },
    { date: "17", day: "Thu", sp: "", dayo: "4" },
    { date: "18", day: "Fri", sp: "Good Friday - Holiday", dayo: " - " },
    { date: "19", day: "Sat", sp: "", dayo: " - " },
    { date: "20", day: "Sun", sp: "", dayo: " - " },
    { date: "21", day: "Mon", sp: "", dayo: "5" },
    { date: "22", day: "Tue", sp: "", dayo: "1" },
    { date: "23", day: "Wed", sp: "", dayo: "2" },
    { date: "24", day: "Thu", sp: "", dayo: "3" },
    { date: "25", day: "Fri", sp: "", dayo: "4" },
    { date: "26", day: "Sat", sp: "", dayo: " - " },
    { date: "27", day: "Sun", sp: "", dayo: " - " },
    { date: "28", day: "Mon", sp: "", dayo: "5" },
    { date: "29", day: "Tue", sp: "", dayo: "1" },
    { date: "30", day: "Wed", sp: "", dayo: "2" },
  ],
  "May '25": [
    { date: "1", day: "Thu", sp: "May Day - Holiday", dayo: " - " },
    { date: "2", day: "Fri", sp: "", dayo: "3" },
    { date: "3", day: "Sat", sp: "", dayo: " - " },
    { date: "4", day: "Sun", sp: "", dayo: " - " },
    { date: "5", day: "Mon", sp: "", dayo: "4" },
    { date: "6", day: "Tue", sp: "", dayo: "5" },
    { date: "7", day: "Wed", sp: "", dayo: "1" },
    { date: "8", day: "Thu", sp: "", dayo: "2" },
    {
      date: "9",
      day: "Fri",
      sp: "Last Working Day - B.Tech - II, IV, VI,VIII, M.Tech - II, IV, M.Tech (Int) - II, IV, VI,VIII",
      dayo: "3",
    },
    { date: "10", day: "Sat", sp: "", dayo: " - " },
    { date: "11", day: "Sun", sp: "", dayo: " - " },
    { date: "12", day: "Mon", sp: "", dayo: " - " },
    { date: "13", day: "Tue", sp: "", dayo: " - " },
    { date: "14", day: "Wed", sp: "", dayo: " - " },
    { date: "15", day: "Thu", sp: "", dayo: " - " },
    { date: "16", day: "Fri", sp: "", dayo: " - " },
    { date: "17", day: "Sat", sp: "", dayo: " - " },
    { date: "18", day: "Sun", sp: "", dayo: " - " },
    { date: "19", day: "Mon", sp: "", dayo: " - " },
    { date: "20", day: "Tue", sp: "", dayo: " - " },
    { date: "21", day: "Wed", sp: "", dayo: " - " },
    { date: "22", day: "Thu", sp: "", dayo: " - " },
    { date: "23", day: "Fri", sp: "", dayo: " - " },
    { date: "24", day: "Sat", sp: "", dayo: " - " },
    { date: "25", day: "Sun", sp: "", dayo: " - " },
    { date: "26", day: "Mon", sp: "", dayo: " - " },
    { date: "27", day: "Tue", sp: "", dayo: " - " },
    { date: "28", day: "Wed", sp: "", dayo: " - " },
    { date: "29", day: "Thu", sp: "", dayo: " - " },
    { date: "30", day: "Fri", sp: "", dayo: " - " },
    { date: "31", day: "Sat", sp: "", dayo: " - " },
  ],
  "Jun '25": [
    { date: "1", day: "Sun", sp: "", dayo: " - " },
    { date: "2", day: "Mon", sp: "", dayo: " - " },
    { date: "3", day: "Tue", sp: "", dayo: " - " },
    { date: "4", day: "Wed", sp: "", dayo: " - " },
    { date: "5", day: "Thu", sp: "", dayo: " - " },
    { date: "6", day: "Fri", sp: "", dayo: " - " },
    {
      date: "7",
      day: "Sat",
      sp: "Bakrid [ Idul Azha ] - Holiday",
      dayo: " - ",
    },
    { date: "8", day: "Sun", sp: "", dayo: " - " },
    { date: "9", day: "Mon", sp: "", dayo: " - " },
    { date: "10", day: "Tue", sp: "", dayo: " - " },
    { date: "11", day: "Wed", sp: "", dayo: " - " },
    { date: "12", day: "Thu", sp: "", dayo: " - " },
    { date: "13", day: "Fri", sp: "", dayo: " - " },
    { date: "14", day: "Sat", sp: "", dayo: " - " },
    { date: "15", day: "Sun", sp: "", dayo: " - " },
    { date: "16", day: "Mon", sp: "", dayo: " - " },
    { date: "17", day: "Tue", sp: "", dayo: " - " },
    { date: "18", day: "Wed", sp: "", dayo: " - " },
    { date: "19", day: "Thu", sp: "", dayo: " - " },
    { date: "20", day: "Fri", sp: "", dayo: " - " },
    { date: "21", day: "Sat", sp: "", dayo: " - " },
    { date: "22", day: "Sun", sp: "", dayo: " - " },
    { date: "23", day: "Mon", sp: "", dayo: " - " },
    { date: "24", day: "Tue", sp: "", dayo: " - " },
    { date: "25", day: "Wed", sp: "", dayo: " - " },
    { date: "26", day: "Thu", sp: "", dayo: " - " },
    { date: "27", day: "Fri", sp: "", dayo: " - " },
    { date: "28", day: "Sat", sp: "", dayo: " - " },
    { date: "29", day: "Sun", sp: "", dayo: " - " },
    { date: "30", day: "Mon", sp: "", dayo: " - " },
  ],
};

export const attendance = [
  {
    code: "21CSE312P",
    title: "Software Engineering in Artificial Intelligence",
    category: "Theory",
    faculty: "Dr. Velliangiri S",
    slot: "A",
    conducted: "24",
    absent: "4",
    percetage: "83.33",
    margin: 2,
  },
  {
    code: "21CSC303J",
    title: "Software Engineering and Project Management",
    category: "Theory",
    faculty: "Dr.Om Prakash P G",
    slot: "B",
    conducted: "24",
    absent: "1",
    percetage: "95.83",
    margin: 6,
  },
  {
    code: "21CSC304J",
    title: "Compiler Design",
    category: "Theory",
    faculty: "Dr.Maheshwari A",
    slot: "C",
    conducted: "27",
    absent: "8",
    percetage: "70.37",
    margin: -5,
  },
  {
    code: "21CSE309J",
    title: "GPU Powered Computing",
    category: "Theory",
    faculty: "Dr.S.Nagadevi",
    slot: "D",
    conducted: "28",
    absent: "4",
    percetage: "85.71",
    margin: 4,
  },

  {
    code: "21CSS303T",
    title: "Data Science",
    category: "Theory",
    faculty: "Dr.P.Saranya",
    slot: "F",
    conducted: "18",
    absent: "5",
    percetage: "72.22",
    margin: -2,
  },
  {
    code: "21MEO106T",
    title: "Introduction to Robotics",
    category: "Theory",
    faculty: "Dr.S.Oliver Nesa Raj",
    slot: "G",
    conducted: "21",
    absent: "3",
    percetage: "85.71",
    margin: 3,
  },
  {
    code: "21CSE309J",
    title: "GPU Powered Computing",
    category: "Practical",
    faculty: "Dr.S.Nagadevi",
    slot: "LAB",
    conducted: "11",
    absent: "0",
    percetage: "100.00",
    margin: 3,
  },
  {
    code: "21LEM302T",
    title: "Indian Traditional Knowledge",
    category: "Practical",
    faculty: "Dr. Kanipriya M",
    slot: "LAB",
    conducted: "16",
    absent: "2",
    percetage: "87.50",
    margin: 2,
  },
  {
    code: "21CSC303J",
    title: "Software Engineering and Project Management",
    category: "Practical",
    faculty: "Dr.Om Prakash P G",
    slot: "LAB",
    conducted: "18",
    absent: "6",
    percetage: "66.67",
    margin: -6,
  },
  {
    code: "21CSC304J",
    title: "Compiler Design",
    category: "Practical",
    faculty: "Dr.Maheshwari A",
    slot: "LAB",
    conducted: "16",
    absent: "4",
    percetage: "75.00",
    margin: 0,
  },
  {
    code: "21CSP302L",
    title: "Project",
    category: "Practical",
    faculty: "Dr. Kanipriya M",
    slot: "LAB",
    conducted: "14",
    absent: "0",
    percetage: "100.00",
    margin: 4,
  },
];
