import {
  Attendance,
  Marks,
  Sidebar,
  TimetableData,
  User,
  UserInfo,
} from "@/Types/type";
import { create } from "zustand";
import { persist } from "zustand/middleware";

export const useSidebar = create<Sidebar>()(
  persist(
    (set) => ({
      isOpen: true,
      toggle: () => set((state) => ({ isOpen: !state.isOpen })),
    }),
    { name: "sidebar" }
  )
);

export const useUser = create<UserInfo>()((set) => ({
  user: {
    roll: "",
    name: "",
    program: "",
    department: "",
    specialisation: "",
    semester: "",
    batch: "",
    section: "",
  },
  marks: [
    {
      name: "Data Science",
      code: "21CSS303T",
      type: "Theory",
      marks: [
        {
          name: "FT-I",
          mark: "5.00",
          total: "5.00",
        },
        {
          name: "FT-II",
          mark: "13.50",
          total: "15.00",
        },
      ],
      credit: "2",
      total: "18.50/20",
    },
    {
      name: "Software Engineering and Project Management",
      code: "21CSC303J",
      type: "Theory",
      marks: [
        {
          name: "FJ-I",
          mark: "14.10",
          total: "15.00",
        },
      ],
      credit: "3",
      total: "14.10/15",
    },
    {
      name: "Compiler Design",
      code: "21CSC304J",
      type: "Theory",
      marks: [
        {
          name: "FJ-I",
          mark: "9.10",
          total: "15.00",
        },
      ],
      credit: "3",
      total: "9.10/15",
    },
    {
      name: "Indian Traditional Knowledge",
      code: "21LEM302T",
      type: "Practical",
      marks: [
        {
          name: "FML-I",
          mark: "28.00",
          total: "30.00",
        },
      ],
      credit: "0",
      total: "28.00/30",
    },
    {
      name: "Software Engineering and Project Management",
      code: "21CSC303J",
      type: "Practical",
      marks: [],
      credit: "3",
      total: null,
    },
    {
      name: "Compiler Design",
      code: "21CSC304J",
      type: "Practical",
      marks: [],
      credit: "3",
      total: null,
    },
    {
      name: "Software Engineering in Artificial Intelligence",
      code: "21CSE312P",
      type: "Theory",
      marks: [],
      credit: "3",
      total: null,
    },
    {
      name: "GPU Powered Computing",
      code: "21CSE309J",
      type: "Theory",
      marks: [
        {
          name: "FJ-I",
          mark: "12.30",
          total: "15.00",
        },
      ],
      credit: "3",
      total: "12.30/15",
    },
    {
      name: "Project",
      code: "21CSP302L",
      type: "Practical",
      marks: [],
      credit: "3",
      total: null,
    },
    {
      name: "Introduction to Robotics",
      code: "21MEO106T",
      type: "Theory",
      marks: [
        {
          name: "FT-I",
          mark: "4.50",
          total: "5.00",
        },
        {
          name: "FT-II",
          mark: "12.80",
          total: "15.00",
        },
      ],
      credit: "3",
      total: "17.30/20",
    },
    {
      name: "GPU Powered Computing",
      code: "21CSE309J",
      type: "Practical",
      marks: [],
      credit: "3",
      total: null,
    },
  ],
  attendance: [
    {
      code: "21CSE312P",
      title: "Software Engineering in Artificial Intelligence",
      category: "Theory",
      faculty: "Dr. Velliangiri S",
      slot: "A",
      conducted: "24",
      absent: "4",
      percetage: "83.33",
      margin: 2,
    },
    {
      code: "21CSC303J",
      title: "Software Engineering and Project Management",
      category: "Theory",
      faculty: "Dr.Om Prakash P G",
      slot: "B",
      conducted: "24",
      absent: "1",
      percetage: "95.83",
      margin: 6,
    },
    {
      code: "21CSC304J",
      title: "Compiler Design",
      category: "Theory",
      faculty: "Dr.Maheshwari A",
      slot: "C",
      conducted: "27",
      absent: "8",
      percetage: "70.37",
      margin: -5,
    },
    {
      code: "21CSE309J",
      title: "GPU Powered Computing",
      category: "Theory",
      faculty: "Dr.S.Nagadevi",
      slot: "D",
      conducted: "28",
      absent: "4",
      percetage: "85.71",
      margin: 4,
    },

    {
      code: "21CSS303T",
      title: "Data Science",
      category: "Theory",
      faculty: "Dr.P.Saranya",
      slot: "F",
      conducted: "18",
      absent: "5",
      percetage: "72.22",
      margin: -2,
    },
    {
      code: "21MEO106T",
      title: "Introduction to Robotics",
      category: "Theory",
      faculty: "Dr.S.Oliver Nesa Raj",
      slot: "G",
      conducted: "21",
      absent: "3",
      percetage: "85.71",
      margin: 3,
    },
    {
      code: "21CSE309J",
      title: "GPU Powered Computing",
      category: "Practical",
      faculty: "Dr.S.Nagadevi",
      slot: "LAB",
      conducted: "11",
      absent: "0",
      percetage: "100.00",
      margin: 3,
    },
    {
      code: "21LEM302T",
      title: "Indian Traditional Knowledge",
      category: "Practical",
      faculty: "Dr. Kanipriya M",
      slot: "LAB",
      conducted: "16",
      absent: "2",
      percetage: "87.50",
      margin: 2,
    },
    {
      code: "21CSC303J",
      title: "Software Engineering and Project Management",
      category: "Practical",
      faculty: "Dr.Om Prakash P G",
      slot: "LAB",
      conducted: "18",
      absent: "6",
      percetage: "66.67",
      margin: -6,
    },
    {
      code: "21CSC304J",
      title: "Compiler Design",
      category: "Practical",
      faculty: "Dr.Maheshwari A",
      slot: "LAB",
      conducted: "16",
      absent: "4",
      percetage: "75.00",
      margin: 0,
    },
    {
      code: "21CSP302L",
      title: "Project",
      category: "Practical",
      faculty: "Dr. Kanipriya M",
      slot: "LAB",
      conducted: "14",
      absent: "0",
      percetage: "100.00",
      margin: 4,
    },
  ],
  timetable: {
    "0": {
      "08:00 - 08:50": {
        title: "Software Engineering in Artificial Intelligence",
        code: "21CSE312P",
        type: "Theory",
        credit: "3",
        room: "TP 303",
        category: "Professional Elective",
      },
      "08:50 - 09:40": {
        title: "Software Engineering in Artificial Intelligence",
        code: "21CSE312P",
        type: "Theory",
        credit: "3",
        room: "TP 303",
        category: "Professional Elective",
      },
      "09:45 - 10:35": {
        title: "Data Science",
        code: "21CSS303T",
        type: "Theory",
        credit: "2",
        room: "TP 403",
        category: "Engineering Science",
      },
      "10:40 - 11:30": {
        title: "Data Science",
        code: "21CSS303T",
        type: "Theory",
        credit: "2",
        room: "TP 403",
        category: "Engineering Science",
      },
      "11:35 - 12:25": {
        title: "Introduction to Robotics",
        code: "21MEO106T",
        type: "Theory",
        credit: "3",
        room: "B301",
        category: "Open Elective",
      },
      "04:50 - 05:30": {
        title: "Project",
        code: "21CSP302L",
        type: "LAB",
        credit: "3",
        room: "UB703",
        category: "Project Course",
      },
      "05:30 - 06:10": {
        title: "Project",
        code: "21CSP302L",
        type: "LAB",
        credit: "3",
        room: "UB703",
        category: "Project Course",
      },
    },
    "1": {
      "12:30 - 01:20": {
        title: "Software Engineering and Project Management",
        code: "21CSC303J",
        type: "Theory",
        credit: "3",
        room: "TP 403",
        category: "Professional Core",
      },
      "01:25 - 02:15": {
        title: "Software Engineering and Project Management",
        code: "21CSC303J",
        type: "Theory",
        credit: "3",
        room: "TP 403",
        category: "Professional Core",
      },
      "02:20 - 03:10": {
        title: "Introduction to Robotics",
        code: "21MEO106T",
        type: "Theory",
        credit: "3",
        room: "B301",
        category: "Open Elective",
      },
      "03:10 - 04:00": {
        title: "Introduction to Robotics",
        code: "21MEO106T",
        type: "Theory",
        credit: "3",
        room: "B301",
        category: "Open Elective",
      },
      "04:00 - 04:50": {
        title: "Software Engineering in Artificial Intelligence",
        code: "21CSE312P",
        type: "Theory",
        credit: "3",
        room: "TP 303",
        category: "Professional Elective",
      },
    },
    "2": {
      "08:00 - 08:50": {
        title: "Compiler Design",
        code: "21CSC304J",
        type: "Theory",
        credit: "3",
        room: "TP 403",
        category: "Professional Core",
      },
      "08:50 - 09:40": {
        title: "Compiler Design",
        code: "21CSC304J",
        type: "Theory",
        credit: "3",
        room: "TP 403",
        category: "Professional Core",
      },
      "09:45 - 10:35": {
        title: "Software Engineering in Artificial Intelligence",
        code: "21CSE312P",
        type: "Theory",
        credit: "3",
        room: "TP 303",
        category: "Professional Elective",
      },
      "10:40 - 11:30": {
        title: "GPU Powered Computing",
        code: "21CSE309J",
        type: "Theory",
        credit: "3",
        room: "TP 703",
        category: "Professional Elective",
      },
      "11:35 - 12:25": {
        title: "Software Engineering and Project Management",
        code: "21CSC303J",
        type: "Theory",
        credit: "3",
        room: "TP 403",
        category: "Professional Core",
      },
      "04:50 - 05:30": {
        title: "Indian Traditional Knowledge",
        code: "21LEM302T",
        type: "LAB",
        credit: "0",
        room: "UB801",
        category: "Mandatory",
      },
      "05:30 - 06:10": {
        title: "Indian Traditional Knowledge",
        code: "21LEM302T",
        type: "LAB",
        credit: "0",
        room: "UB801",
        category: "Mandatory",
      },
    },
    "3": {
      "08:00 - 08:50": {
        title: "Software Engineering and Project Management",
        code: "21CSC303J",
        type: "LAB",
        credit: "3",
        room: "UB703",
        category: "Professional Core",
      },
      "08:50 - 09:40": {
        title: "Software Engineering and Project Management",
        code: "21CSC303J",
        type: "LAB",
        credit: "3",
        room: "UB703",
        category: "Professional Core",
      },
      "12:30 - 01:20": {
        title: "GPU Powered Computing",
        code: "21CSE309J",
        type: "Theory",
        credit: "3",
        room: "TP 703",
        category: "Professional Elective",
      },
      "01:25 - 02:15": {
        title: "GPU Powered Computing",
        code: "21CSE309J",
        type: "Theory",
        credit: "3",
        room: "TP 703",
        category: "Professional Elective",
      },
      "02:20 - 03:10": {
        title: "Software Engineering and Project Management",
        code: "21CSC303J",
        type: "Theory",
        credit: "3",
        room: "TP 403",
        category: "Professional Core",
      },
      "04:00 - 04:50": {
        title: "Compiler Design",
        code: "21CSC304J",
        type: "Theory",
        credit: "3",
        room: "TP 403",
        category: "Professional Core",
      },
      "04:50 - 05:30": {
        title: "GPU Powered Computing",
        code: "21CSE309J",
        type: "LAB",
        credit: "3",
        room: "NA",
        category: "Professional Elective",
      },
      "05:30 - 06:10": {
        title: "GPU Powered Computing",
        code: "21CSE309J",
        type: "LAB",
        credit: "3",
        room: "NA",
        category: "Professional Elective",
      },
    },
    "4": {
      "09:45 - 10:35": {
        title: "Compiler Design",
        code: "21CSC304J",
        type: "Theory",
        credit: "3",
        room: "TP 403",
        category: "Professional Core",
      },
      "10:40 - 11:30": {
        title: "Data Science",
        code: "21CSS303T",
        type: "Theory",
        credit: "2",
        room: "TP 403",
        category: "Engineering Science",
      },
      "11:35 - 12:25": {
        title: "GPU Powered Computing",
        code: "21CSE309J",
        type: "Theory",
        credit: "3",
        room: "TP 703",
        category: "Professional Elective",
      },
      "01:25 - 02:15": {
        title: "Compiler Design",
        code: "21CSC304J",
        type: "LAB",
        credit: "3",
        room: "UB1209",
        category: "Professional Core",
      },
      "02:20 - 03:10": {
        title: "Compiler Design",
        code: "21CSC304J",
        type: "LAB",
        credit: "3",
        room: "UB1209",
        category: "Professional Core",
      },
    },
  },
  loading: true,
  setUser: (data: User) => set({ user: data }),
  setMarks: (data: Marks) => set({ marks: data }),
  setAttendance: (data: Attendance) => set({ attendance: data }),
  setTimetable: (data: TimetableData) => set({ timetable: data }),
  setLoading: (data: boolean) => set({ loading: data }),
}));
